### ISSUE TITLE
저장 공간

### ISSUE THREAD

**Issue by SeungpilPark** [TheOpenCloudEngine/uEngine-cloud#1]
## Redis - 퍼시스턴스 인스턴스 (위치 고정 도커, 볼륨 마운팅)
 - 볼륨 마운팅에 의해 데이터는 보존되지만, 휘발되어도 상관없는 데이터로 구성된다.
 - Zuul 라우터 룰 캐쉬 : From BPMN
 - Zuul 인증정보 캐쉬 : From IAM
 - Zuul 라우터 정보(블루,그린) 캐쉬 : From Gitlab, Mesos

## Gitlab
 - 정적인 데이터로 구성되며, 자주 업데이트 될 가능성이 적고, gitlab 페이지에서 수정할 경우 유지보수에 용이한 데이터로 구성된다.

 - App 구성 정보
   - 소유자
   - 깃랩 프로젝트 아이디
   - prod,dev,stg 배포 상태
   - prod,dev 블루그린 상태
   - 호스트 정보
   - Mesos 디플로이 컨피그
   - vcap services
   - 런타임 :
     - App 생성 단계
     - App 타임라인

 - Cloud config 레파지토리

<예>
```
dcos:
  apps:
    uengine-eureka-client:
      number: 1
      appType: springboot
      owner: root
      gitlab:
        projectId: 1
      prod:
        commit-sha:
        active: false
        marathonAppId: /uengine-eureka-client-blue
        external: api.uengine.io/uengine-eureka-client
        internal: marathon-lb-internal.marathon.mesos:10002/uengine-eureka-client
        deployment: blue
      stg:
        commit-sha:
        active: false
        enableRollback: false
        marathonAppId: /uengine-eureka-client-green
        external: api-stg.uengine.io/uengine-eureka-client
        internal: marathon-lb-internal.marathon.mesos:10003/uengine-eureka-client
        deployment: green
      dev:
        commit-sha:
        active: false
        marathonAppId: /uengine-eureka-client-dev
        external: api-dev.uengine.io/uengine-eureka-client
        internal: marathon-lb-internal.marathon.mesos:10004/uengine-eureka-client
        deployment: dev
```

<단점> 
  - 다수의 앱 운영/설정 변경 시 깃랩의 커밋히스토리가 늘어난다.
  - 소수의 운영자에 의해 private 으로 운영시에만 할 수 있는 아키텍쳐
  
<img width="1044" alt="2017-11-14 11 16 59" src="https://user-images.githubusercontent.com/13447690/32759579-74337c7e-c92d-11e7-93fa-ba6628ee6964.png">
