### ISSUE TITLE
zuul 어플리케이션 화

### ISSUE THREAD

**Issue by SeungpilPark** [TheOpenCloudEngine/uEngine-cloud#11]
# zuul 어플리케이션 화

## 생성시 화면 옵션

- 라우터 이름. ex) snc-router
- 기본 라우트 주소 ex) snc-api.pas-mini.io
- 기본 라우트 주소 설정시 snc-api-dev,snc-api-stg 가 추가로 생성.

## 생성및 운영 방식

- 기존 어플과 동일한 컨피그로..
- zuul 템플릿이 필요
- zuul 템플릿 교체 대상: 어플리케이션 이름, pom 파일
- 클라우드 콘피그는 dev,stg,prod 생성이 될 것임.
- 콘피그에서 zuul 세팅 조정함.
- deploy.json 에는 SPRING_APPLICATION_NAME,APPLICATION_NAME,PROFILE,SPRING_PROFILES_ACTIVE 이 들어감.
- 이 앱은, 자신의 롤이 곧 PROFILE 이다. 자신의 PROFILE 에 해당하는 앱들만 통과시킨다.

## 줄,리본 설정 값들

```
zuul:
  addProxyHeaders: true

  routes:
    customer:
      path: /customer/**
      serviceId: insurance-service
      stripPrefix: false
    vehicle:
      path: /vehicle/**
      serviceId: insurance-service
      stripPrefix: false
    vehicle-detail:
      path: /vehicle-detail/**
      serviceId: gmv-service
      stripPrefix: false

endpoints:
  routes:
    sensitive: false

ribbon:
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 1
  OkToRetryOnAllOperations: true
  ServerListRefreshInterval: 2000
  ConnectTimeout: 10000
  ReadTimeout: 10000
```
