### ISSUE TITLE
멀티 서비스 in One project

### ISSUE THREAD

**Issue by SeungpilPark** [TheOpenCloudEngine/uEngine-cloud#12]
# 멀티 서비스 in One project

멀티 컨테이너 서비스

dev,stg,prod(blue,green) 이 각각 맵타입으로 관리되야 한다.
맵타입의 키는 프로젝트 내의 서비스 이름으로 관리된다.

프로젝트 내의 서비스는 각각 독립된 dcos-app 및 설정 풀을 가지고 있다.
ci 는 프로젝트 내의 서비스마다 빌드,도커빌드가 추가로 붙는다.
ci 의 디플로이 스크립트는 멀티플로 호출하도록 한다.
ci 의 디플로이 스크립트 멀티플 호출은 패럴로 호출한다.

## 서비스 디파인

 - 프로젝트 내에서 서비스를 지정하는 방법

```
---
dcos:
  apps:
    hello-world:
      appType: "multi"
      services:
        - definition
        - bpm
        - zuul-router
        - front-end
      gitlab:
        projectId: 30
      iam: "darkgodarkgo@gmail.com"
      owner: "darkgodarkgo"
```
