### ISSUE TITLE
Zuul cors,auth options

### ISSUE THREAD

**Issue by SeungpilPark** [TheOpenCloudEngine/uEngine-cloud#13]
# auth option

- Zuul 을 통해 iam 과 통신한다.
- Zuul 의 /iam 은 iam 서비스 아이디로...

인증 옵션을 위해 필요한 것들

 - iam 주소
 - iam 매니지먼트,시크릿 키

**Comment by jinyoung** [comment]
![zuul ui](https://user-images.githubusercontent.com/487999/34349654-bafb6db2-ea55-11e7-8a71-d6d31534c99c.png)

Zuul  application.yml 설정 예시
```
zuul:
  addProxyHeaders: true
  addCorsHeaders: true

  routes:
    definition:
      path: /definition/**
      serviceId: definition
      stripPrefix: false
    instance:
      path: /instance/**
      serviceId: bpm
      stripPrefix: false
    instance-entity:
      path: /instances/**
      serviceId: bpm
      stripPrefix: false
    worklist-entity:
      path: /worklist/**
      serviceId: bpm
      stripPrefix: false
    instance-workitem:
      path: /work-item/**
      serviceId: bpm
      stripPrefix: false
    metadata:
      path: /classdefinition/**
      serviceId: bpm
      stripPrefix: false


```

**Comment by jinyoung** [comment]
서비스 목록 가져오는 기능은  https://github.com/TheOpenCloudEngine/uEngine5-base/blob/01084e029c6cfa1b233135a35d8dfbcae5281170/front-end/src/components/bpmn/role/Role.vue

참고

** 이게 되려면 global zuul 설정에서 다음이 추가되거나 uEngine-cloud-server 가 이를 proxy 해주어야 함:

```
zuul:
    eureka:
      path: /eureka/**
      url: ${eureka.client.serviceUrl.defaultZone}
      stripPrefix: true

```

**Comment by SeungpilPark** [comment]
## 줄 컨피그레이션 참조

[https://cloud.spring.io/spring-cloud-netflix/multi/multi__router_and_filter_zuul.html](https://cloud.spring.io/spring-cloud-netflix/multi/multi__router_and_filter_zuul.html)

**Comment by SeungpilPark** [comment]
## Zuul 과 IAM 의 연관관계를 고려한 yml 풀 세팅

### IAM 세팅

```
management:
  security:
    enabled: false

security:
  basic:
    enabled: false
  ignored: /**
  password:
    encoder:
      secret1: Bar12345Bar12345
      secret2: ThisIsASecretKet

spring:
  security:
    enabled: false
  data:
    rest:
      basePath: /api/v1

server:
  port: 8080
  servletPath: /

---
# =============================================
#  레파지토리 - 데이터 베이스 정보입니다.
# =============================================

spring:
  profiles: local
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/msa
    username: root
    password:

# =============================================
#  레파지토리 - 커스텀 사용자 데이터 프로바이더 클래스입니다.
#            디폴트로 제공되는 JPA Repository 클래스를 수정할 수 있습니다.
# =============================================
user-provider:
  interface: org.uengine.cloud.user.UserRepository
  

# ========================================
#  IAM 시스템 Configuration
# ========================================

system:
# 어드민 정보
  admin:
    username: admin
    password: admin
# jwt 발급 정보 및 키    
  jwt:
    key: fcf5afd7-be51-4dfc-949f-d4ab768b985d
    issuer: ${spring.application.name}
    oldrefreshtoken-timeout: 60
# 시스템 이메일 정보 (옵셔널)
  mail:
    html: false
    host: smtp.gmail.com
    username: flamingo.workflow@gmail.com
    password: princoprinco9
    port: 587
    smtp:
      auth: true
      starttls:
        enable: true
    from:
      address: sppark@uengine.org
      name: uengine
    contacts:
      address: sppark@uengine.org
      redirect:
        address: http://localhost:8080

# =============================================
#  스코프 - 주로 백엔드 서비스에 해당됩니다.
# =============================================
scope:
  - name: definition
    description: 디자이너 서비스의 접근을 허용합니다.

  - name: bpm
    description: bpm 서비스의 접근을 허용합니다.


# =============================================
#  클라이언트 - 주로 프론트 엔드 어플리케이션에 해당됩니다.
# =============================================
client:
  - name: uEngine5
    description: uEngine5 Bpm Application
    clientKey: my-client-key
    clientSecret: my-client-secret

    # 토큰 발급시 요청할 수 있는 스코프 목록.
    enable-scopes: definition,bpm

    # client-key,client-secret 헤더로 Rest api 를 호출할 수 있는 권한.
    # 회원 가입,사용자 정보 수정등의 rest api 를 호출할 수 있다.
    # 서드파티 어플리케이션은 권한을 주면 안되고, 오피셜 어플리케이션은 권한을 가지는것을 추천.
    access-rest-enable: true

    # 클라이언트 활성화 여부
    activeClient: true

    # 지원하는 그런트 타입.
    authorizedGrantTypes: code,implicit,password,credentials

    # code,implicit 방식의 로그인일 때 리다이렉트 되는 주소.
    webServerRedirectUri: http://front-end.pas-mini.io#login-redirect

    # 리프레쉬 토큰 발급.
    refreshTokenValidity: true

    # 만기 토큰 자동 삭제.
    autoDeletionToken: true

    # JWT 토큰 콘텍스트에 포함될 정보 : clientId,clientKey,managementId,scopes,type,refreshToken,userName,userId,user
    requiredContext: clientId,clientKey,managementId,scopes,type,refreshToken,userName,userId,user

    # JWT 토큰 알고리즘: HS256 or RS256
    jwtAlgorithm: HS256

    # code 인증 방식의 유지시간.
    codeLifetime: 36000

    # 리프레쉬 토큰 유효시간
    refreshTokenLifetime: 2592000

    # 어세스 토큰 유효시간
    accessTokenLifetime: 3600




# ======================
#  Eureka Configuration
# ======================

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
  instance:
    statusPageUrlPath: ${server.servletPath}info
    healthCheckUrlPath: ${server.servletPath}health
    metadataMap:
        deployment: local
        profile: local

```

### IAM 과 연관된 예상 Zuul 풀세팅

```
# ========================================
#  IAM 연동 Configuration
# ========================================

iam:
# 접속 정보
  host: http://my-iam-dev.pas-mini.io
# 어드민 정보 - zuul 은 iam 의 루트 권한으로 접근.
  admin:
    username: admin
    password: admin

zuul:
  # 프록시 서버 정보를 헤더에 주입
  addProxyHeaders: true
  # Cors 를 헤더에 주입
  addCorsHeaders: true  

  routes:
    # 라우트명
    definition:
      # 패스명
      path: /definition/** 
     # serviceId 와 url 는 두가지가 공존할 수 없음.
      serviceId: definition   # 서비스 ID
      url: 'http://aaa.bb.com/abc'   # url
      # 체크박스 (Strip Prefix)
      stripPrefix: false
      # (옵셔널) 토큰에 definition 스코프가 있어야만 통과.
      required-scopes: definition
    instance:
      path: /instance/**
      serviceId: bpm
      stripPrefix: false
    instance-entity:
      path: /instances/**
      serviceId: bpm
      stripPrefix: false
    worklist-entity:
      path: /worklist/**
      serviceId: bpm
      stripPrefix: false
    instance-workitem:
      path: /work-item/**
      serviceId: bpm
      stripPrefix: false
    metadata:
      path: /classdefinition/**
      serviceId: bpm
      stripPrefix: false
```

- 꼼꼼히 읽기:
  - 리본 컨피그레이션: 타임아웃, 재시도 회수 등등도 파악하기.
  - 파일 업로드 관련 세팅 파악하기
  - None Eureka Service: 유레카 서비스가 아닌 것도 라우트에 추가가 가능해야함
     - 리본의 listOfServers 옵션으로 가능하게 한다.
     - 레거시 rest 서버
     - Http 기반 DB 서비스 (Redis, CouchBase, HBase etc...)
     - 기타 현업에서 일어날 수 있는 외부 연동 rest 서비스
     - 소셜 / 클라우드 서비스
