### ISSUE TITLE
Organization Group 관련 추가사항

### ISSUE THREAD

**Issue by Lusky87** [TheOpenCloudEngine/uEngine-cloud#17]
## Organization Group관련 추가사항

- Organization 관련하여 팀별로 앱을 관리할 수 있도록 하시길바라는것같아 정확한 요구사항에 대해 확인코자합니다.

### 1. 현재 organization의 구성상태는 iam에서 acl을 admin / user로 구분하여 관리하고있으며 각각의 권한의 기능은 아래와 같습니다.

|	 | Admin 				| User			 |
|--------|--------|-------|
|Organization	 |모든유저의 정보확인 및 유저생성,삭제가능	   |Organization확인불가	|
|App	 |모든앱을 확인 및 수정,삭제 할 수 있음	   |본인의 앱만 확인 및 수정,삭제 가능	|
|Service|모든 서비스를 확인 및 수정,삭제 할 수 있음|서비스 확인 불가|

또한 iam정보는
~~~
{
  "subscription_id": "1da17731-ae8f-4c34-8377-8c71378d3837",
  "acl": "admin",   <------- 이부분을 추가하여 저장합니다.
  "billing_account_id": "ef87d762-ddc1-435c-9d9c-c5abd1b1691f",
  "level": 5,
  "billing_organization_id": "eb381e88-c81f-4c86-919a-9aa540009c2f",
  "email": "jyjang@uengine.org",
  "_attachments": {
    "avatar": {
      "content_type": "image/jpeg",
      "revpos": 48,
      "digest": "md5-kPoZLaOPMJ9UMbriHhcBXQ==",
      "length": 23223,
      "stub": true
    }
  },
  "name": "장진영",
  "userName": "jyjang@uengine.org"
}
~~~
위와 같이 구성되어있습니다.

### 2. 추후 Organization예상구성은

Gitlab의 그룹 api를 이용하여 해당그룹의 소속자들은 그룹소속의 app들을 모두 확인 할 수 있으며 해당 그룹소속이 아닌 user들은 본인이 작성한 앱만을 볼 수 있도록 구성할 예정입니다.

|	         | Admin     | Group User    |  User |
|--------- |----------|--------------|-------|
|Organization|모든유저의 정보확인 및 유저생성,삭제가능|Group 내부의 유저들만 확인 가능| 본인만 확인 및 수정가능 |
|App	 |모든앱을 확인할 수 있음	   |본인이 속한 그룹의 앱만 확인 및 수정 삭제가능	| 본인의 앱만 확인 및 수정 삭제 가능 |
|Service|모든 서비스를 확인할 수 있음|서비스 확인 불가| 서비스 확인 불가 |

이러한 상황에 대해서 정확한 요구사항의 파악이 필요하여 issue를 작성하게 되었습니다.

**Comment by Lusky87** [comment]
####대표님 말씀으로는 IAM과 Gitlab간의 SSO(Single Sign-On)가 되면 
- gitlab 을 사용하여 그룹이 지정되거나 프로젝트에 배정되는 인원들이 모두 Organization에서 볼 수 있어야 한다고 하심. (gitlab과 같이 그룹,프로젝트 인원 배정이 진행될 수 있어야함)
- SSO 여부가 중요하나 gitlab 에서 group, member of group정보를 모두 가져올 수 있도록 만들어주는 것이 좋을듯.

**Comment by SeungpilPark** [comment]
## 이작업을 위해 해야할 것:

기존 dcos-apps.yml 에 owner 는 깃랩 유저네임을 뜻함.

```
    chatbot:
      appType: "springboot"
      dev:
        active: true
        commit-sha: ""
        config-changed: true
        deployment: "dev"
        external: "chatbot-dev.pas-mini.io"
        internal: "marathon-lb-internal.marathon.mesos:10025"
        marathonAppId: "/chatbot-dev"
        service-port: 10025
      gitlab:
        projectId: 74
      iam: "darkgodarkgo@gmail.com"
      number: 5
      owner: "darkgodarkgo"
      prod:
        active: true
        commit-sha: ""
        config-changed: true
        deployment: "green"
        external: "chatbot.pas-mini.io"
        internal: "marathon-lb-internal.marathon.mesos:10023"
        marathonAppId: "/chatbot-green"
        service-port: 10023
      stg:
        active: true
        commit-sha: ""
        config-changed: true
        deployment: "stg"
        external: "chatbot-stg.pas-mini.io"
        internal: "marathon-lb-internal.marathon.mesos:10024"
        marathonAppId: "/chatbot-stg"
        service-port: 10024

```
## IAM 메타데이터가 다음을 가져야 함

 - 깃랩 유저 아이디

## IAM 로직에 다음이 추가되야함.

 - IAM 사용자 생성시 메타데이터에 깃랩 유저 아이디를 생성.
 - 이미 생성된 IAM 아이디들은 수작업으로 깃랩 유저 아이디 매핑.

## 프로젝트 생성시 깃랩 그룹 선택란을 추가.

 - 본인이 속한 그룹을 선택 가능.
 - CreateAppJob 에서 TODO (namespace) 를 그룹으로 선택.

## dcos-apps.yml 변경 및 프로젝트 바로가기

- owner 는 파기하도록 한다. (IAM 에서 관리.)
- UI 에서 소스코드 바로가기 버튼 클릭시, gitlab.projectId 로 프로젝트를 얻어와서, 정확한 패스로 윈도우를 열어주도록 한다. (현재는 owner 패스로 바로 보내기로 되어있음.)
- UI 에서 파이프라인 클릭시도 마찬가지.
