### ISSUE TITLE
어플라이언스 설치 자동화 / 운영 자동화

### ISSUE THREAD

**Issue by SeungpilPark** [TheOpenCloudEngine/uEngine-cloud#2]
# 설치 자동화

## 설치 자동화 툴 비교

<img width="1185" alt="2017-12-01 1 13 18" src="https://user-images.githubusercontent.com/13447690/33467686-a06e2d92-d699-11e7-9205-2789b15cbc5a.png">

프로비저닝 툴을 오랜만에 공부해보니, Docker 때문에 프로비져닝 툴 시장자체가 신규제품이 안나오고있고, 그나마 있는 제품도 인프라 구성(Pass,Hadoop) 용도로 전락해버렸다.

클라우드 애플리케이션 부품들을 환경구성을 마춰서 이리저리 설치, 배포 한다는 개념이 모두 도커때문에 망해버림.

프로비져닝 툴이 프로비져닝만 잘하면 됬지 온갖 자기네들만의 클라우드 기법들을 녹여내서 클라우드 오케스트레이터처럼 동작하는데 문서 보기도 짜증나고 배우고싶지도 않음. 우리가 원하는건 딱 프로비져닝만 할 수 있으면 됨.

## 우리가 원하는 작업

1. 인터넷 격리공간에서 설치가 되야함.

2. 모든 구성요소가 다 들어있는 Zip 파일을 들고다니거나(IDC 등 격리공간), git 을 통해 구성요소를 다운받음(인터넷 가능공간)

3. 프로비져닝 데피니션 파일을 작성함.

```
## 데피니션 예시
dcos:
  master:
  - 172.1.0.1
  - 172.1.0.2
  - 172.1.0.3
  agent-private:
  - 172.1.0.4
  - 172.1.0.5
  - 172.1.0.6
  - 172.1.0.7
  - 172.1.0.8
  agent-public:
  - 172.1.0.10
  service-hosts:
     cloud-config: config.pass-mini.io
     eureka-server: eureka-server.pass-mini.io
     zuul-prod: api.pass-mini.io
     zuul-dev: api-dev.pass-mini.io
     zuul-stg: api-stg.pass-mini.io
     cloud-orchestrator: cloud-server.pass-mini.io
     cloud-orchestrator-ui: cloud.pass-mini.io

gitlab:
  usePreInstalled: false
  ip: 172.1.0.20
  fqdn: gitlab.pass-mini.io
  smtp:
     host: google.gmail.com....
     username: ....
     password: ....

kibana:
  ip: 172.1.0.21

elastick-search:
  ip: 172.1.0.21
```

4. 프로비져닝 실행 스크립트는 기본 단계들만 구성
 - pre-install.sh  :  프로비져닝 전에 환경체크.
 - install.sh  :  프로비져닝 실행.
 - post-install.sh : 프로비져닝 후 구성요소 헬스 체크.

## 세상에서 제일 심플한 프로비져닝 툴 찾기

현재까지 Ansible 이라는 놈이 json, yml 로 데피니션을 꾸밀수 있고 제일 심플해보임(프로비져닝 이외에 딴짓을 안한다.)

# 클러스터 운영 자동화, 클러스터 운영 CLI

클러스터 운영 cli 는 다음의 기능을 가져야함. 

- 클러스터 설치 정보 백업
- 에이전트 추가 설치, 삭제
- 마스터 추가 설치,삭제
- 서비스 구성요소 헬스 체크
- 서비스 구성요소 로그 테일 (mesos-dns,mesos,marathon,haproxy etc..)
