### ISSUE TITLE
Zuul working with IAM

### ISSUE THREAD

**Issue by SeungpilPark** [TheOpenCloudEngine/uEngine-cloud#31]
Zuul 옵션 사항들.

```
---
zuul:
  ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin
  addProxyHeaders: true

  # Decides to check the token.
  iam-authentication: true

  # Key to determine if the token's signature is correct.
  # It must be the same key that IAM used to issue the token.
  # Copy and paste from your IAM's iam.jwt.key
  iam-jwt-key: my-jwt-encrypt-key-my-jwt-encrypt-key

  routes:
    order:
      path: /orders/**
      serviceId: order-service
      stripPrefix: false
      # Check whether the user's metadata also has a scope.
      iam-user-scopes-check: false
      # List of scopes needed for this path
      iam-scopes:
        - guest/GET
        - catalog-order/PUT-PATCH-POST-DELETE

    # If no iam-scopes, all request will be passed.
    customer:
      path: /customers/**
      serviceId: customer-service
      stripPrefix: false


    item:
      path: /items/**
      serviceId: order-service
      stripPrefix: false
      iam-user-scopes-check: false
      iam-scopes:
        - guest/GET
        - catalog-manage/PUT-PATCH-POST-DELETE
```
