### ISSUE TITLE
파이프라인

### ISSUE THREAD

**Issue by SeungpilPark** [TheOpenCloudEngine/uEngine-cloud#5]
<img width="815" alt="2017-11-14 4 55 59" src="https://user-images.githubusercontent.com/13447690/32768817-c93d3866-c95c-11e7-8f9e-8768704b79d9.png">

### 생성시  필요정보들
- categoryItemId,
- cpu: 0.4,
- mem: 512,
- instances: 1,
- appNumber: 1,
- projectId: "",
- appName: null,
- externalProdDomain: null,
- externalStgDomain: null,
- internalProdDomain: null,
- internalStgDomain: null

### 밸리데이션
- appName 중복 체크
- 깃랩 프로젝트, 러너체크

 1. dcos app 생성. => dcos-apps.yml (dev active)
 2. deployment/<appName>/create.json 생성.

```
 {
  status: repository-create
  definition: { 필요 정보들}
}
```
3. 리턴

### 프로젝트 포크

1. template/<categoryItemId>/definition.json 을 참조하여, mustache 엔진을 사용해 값 교체.

```
{
   projectId:
   mappings: [
     {
         path: "src/main/../resources/bootstrap.yml"
         file: "file/bootstrap.yml"
     }
   ]
}

- 파일들
  - ci.yml
  - application.yml
  - bootstrap.yml
  - Dockerfile
  - ci-test.sh
  - ci-deploy-stg.json
  - ci-wait-confirm.sh
```

2. 포크 후 콘텐트 교체. 교체할 파라미터 셋은
- config url
- appName 어플리케이션 이름
- uengine-cloud 호스트

3. 러너 등록. 웹훅 등록. 파이프라인 실행. 스테이터스 변경

웹훅 등록: 필요.
러너 등록: 필요
파이프라인 트리거 등록: 사용자 이름으로 등록 필요. (Sudo)
파이프라인 api 는 Sudo 사용자 이름으로 함.
트리거 api 는 트리거 소유주로 트리거가 발생함.

웹훅 발생시:
=> 커밋일 경우
=> 커밋마다 dev,production run 여부는 config server 가 가지고있음.
=> api 실행(dev), 트리거 실행(production) 구분법.

```
 {
   status: repository-create-success or repository-create-failed
   definition: {}
}
```

## 앱 삭제

1.메소스 앱들을 가져온 후, 모두 지운다.
2.깃랩 프로젝트는 옵션으로 지울지 말지 정한다.
3.dcos-apps 에 해당 정보 삭제.
4.deployment/<appName>/create.json 삭제.

## 파이프라인 컨트롤

1. gitlab 파이프라인 api, job api 사용.

## 딜리버리
- [ci skip] 이 커밋에 있을 경우 건너뛰게 된다.
- 빌드, 스테이징 배치, 테스트,테스트 컨펌, 프로덕션 배치

### 입력 단계 - ui 로만 존재
- 깃 주소(고정)
- 브런치
- 옵션
   - 이 변경사항을 Git에 푸시할 때마다 작업 실행 
   - 이 단계를 수동으로 실행할 때만 작업 실행 => [ci skip] 으로 대체

### 변수
variables:
  UENGINE_CLOUD_URL: "http://183.101.9.177:8080"

### 빌드

```
maven-build:
  image: maven:3-jdk-8
  stage: build
  only:
    - master
  script: "mvn package -B"
  artifacts:
    paths:
      - target/*.jar
```

### 도커 빌드

```
docker-build:
  stage: package
  only:
    - master
  script:
    - docker build --build-arg CI_PROJECT_NAME=${CI_PROJECT_NAME} --build-arg CI_COMMIT_SHA=${CI_COMMIT_SHA} -t gitlab.uengine.io:5000/${CI_PROJECT_NAME}:v1 .
    - docker push gitlab.uengine.io:5000/${CI_PROJECT_NAME}:v1
    - docker rmi gitlab.uengine.io:5000/${CI_PROJECT_NAME}:v1
```

### 스테이징 배치

1. 스테이징 app 검색
2. 없으면 신규, 있으면 update 명령어(force)
3. 201 이거나 200 이 아니면 exit 1
4. app 상태가 health 일때까지 기다림.
5. 5분이상 지속시 exit 1

```
deploy-staging:
  image: nhoag/curl
  stage: staging
  only:
    - master
  script:
    - sh ./ci-deploy-staging.sh
```

        //테스트
        //스테이징에 배치된 컨테이너를 대상으로 테스트함.
        //테스트 이미지
        //테스트 스크립트 및 셀레니움
        //- 옵션
        // 이 작업이 성공 후 관리자의 승인을 받아야 다음단계 진행

        //사용자 인증이 안되있으면 curl 후 인증이 필요하면 스스로 job_id 를 사용해 캔슬.
        //ui 에서 사용자 인증 클릭시 job_id resume.
        //리섬된 잡은 사용자 인증이 되어있으면 컴플리트 처리함.
        
        //프로덕션 배치
        //- 배치 옵션(json)
        // - 라우팅 옵션
        // 기존 프로덕션에서 신규 프로덕션으로 순차적으로 라우팅
        //   - 듀레이션 (시간)
        // 기존 프로덕션을 바로 신규 프로덕션으로 라우팅

        //curl 로 프로덕션 배치를 요청하고, 스크립트 대기하는 로직이 필요.

        //========
        //프로덕션 배치 내부 로직
        // 스테이징: <appName>-stg
        // 개발(이전) :<appName>-prod-green
        // 개발(신규) :<appName>-prod-blue

        //Zuul 시나리오
        //deployment/<appName>/pipeline.yml => 배치 라우팅 룰.

        //Zuul 순차 라우팅
        //프로덕션 배치 순서가 올 경우
        //----------------------
        // 이전 프로덕션이 있을 경우 (green)
        // <appName>-prod-blue 를 생성한다.
        // green 퍼센트 감소. blue 퍼센트 증가시킨다.
        // 모든 퍼센트가 끝났을 때, dcos-apps 에 prod 를 blue 로 등록한다.
        // 라우트 리프레쉬 한다.
        // green 을 삭제한다.

        //----------------------
        // 이전 프로덕션이 있고, 순차 라우팅이 아닐 경우(green)
        // <appName>-prod-blue 를 생성한다.
        // dcos-apps 에 prod 를 blue 로 등록한다.
        // 라우트 리프레쉬 한다.
        // green 을 삭제한다.

        //----------------------
        // 이전 프로덕션이 없을 경우 (green)
        // <appName>-prod-green 를 생성한다.
        // dcos-apps 에 prod active, green 으로 등록한다.
        // 라우트 리프레쉬

        //폴리글랏 haproxy
        //----------------------
        // 이전 프로덕션이 있을 경우 (green)
        // <appName>-prod-blue 를 생성한다. (haproxy 는 green 으로 쏘고있음)
        // green 을 삭제한다. (haproxy 는 blue 로 쏨)
        // dcos-apps 에 prod 를 blue 로 등록한다.
