### ISSUE TITLE
ELK Metrics && Log

### ISSUE THREAD

**Issue by SeungpilPark** [TheOpenCloudEngine/uEngine-cloud#63]
## 오버뷰

![elkv5](https://user-images.githubusercontent.com/13447690/36365785-6f0893c6-158e-11e8-8d05-dc5b62d7fd90.png)

## Docker compose install

```
$ sudo curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` -o /usr/bin/docker-compose

$ sudo chmod +x /usr/bin/docker-compose

$ docker-compose --version
```

## Docker compose uninstall

```
$ sudo rm /usr/bin/docker-compose
```

## ELK install

```
$ git clone https://github.com/deviantony/docker-elk
$ cd docker-elk
$ sudo docker-compose up
```

## compose env 변경

```
$ vi .env

# ./.env
# for our staging environment
COMPOSE_HTTP_TIMEOUT=120
```

## compose yml 세팅

```
version: '2'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.1
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - /home/centos/data-elk:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx1024m -Xms1024m"

  logstash:
    image: docker.elastic.co/logstash/logstash-oss:6.2.1
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "5000:5000"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.2.1
    volumes:
      - ./kibana/config/:/usr/share/kibana/config:ro
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
```

## compose 실행

```
sudo docker-compose up -d
```
