### ISSUE TITLE
Gitlab root password 관리

### ISSUE THREAD

**Issue by SeungpilPark** [TheOpenCloudEngine/uEngine-cloud#72]
- root 패스워드 분실/해킹시 해결법

[https://docs.gitlab.com/ee/security/reset_root_password.html](https://docs.gitlab.com/ee/security/reset_root_password.html)

- root 패스워드 하드코딩 요소 => 1군데 발견
  - cloud config server git repository url

```
spring:
  cloud:
    config:
      server:
        git:
          uri: http://@host.gitlab@/root/cloud-config-repository.git
          username: root
          password: adminadmin
```

root 패스워드 관리시에는 패스워드 변경 후 cloud config server 정보도 변경 후 재시작해야 한다.
