### ISSUE TITLE
Zuul upgrade to iam-2.0.1, Decode secure metadata field

### ISSUE THREAD

**Issue by SeungpilPark** [TheOpenCloudEngine/uEngine-cloud#84]
## Encryption and Decryption Metadata field 

- Sync  parameters IAM and Zuul.

---
**IAM**

```
iam:
  jwt:
    key: my-jwt-encrypt-key-my-jwt-encrypt-key
    metadata-encoder-secret1: Bar12345Bar12345
    metadata-encoder-secret2: ThisIsASecretKet
    secure-metadata-fields:
      - "$.gitlabToken"
```

---
**Zuul**

```
zuul:
  iam-jwt-key: my-jwt-encrypt-key-my-jwt-encrypt-key
  metadata-encoder-secret1: Bar12345Bar12345
  metadata-encoder-secret2: ThisIsASecretKet
  secure-metadata-fields:
    - "$.gitlabToken"
```

---
- `iam-jwt-key` is JWT signature key. It is used to check whether the token is forged or not.
- `metadata-encoder-secret1,2` is used to encrypt certain metadata fields in the AES128 encryption format to prevent exposure to JWT tokens.
- `secure-metadata-fields` is a list of metadata fields to be decrypted, expressed in [JsonPath syntax](https://github.com/json-path/JsonPath).

** metadata JsonPath Examples**
-------------

Given the json

```javascript
{
    "store": {
        "book": [
            {
                "category": "reference",
                "author": "Nigel Rees",
                "title": "Sayings of the Century",
                "price": 8.95
            },
            {
                "category": "fiction",
                "author": "Evelyn Waugh",
                "title": "Sword of Honour",
                "price": 12.99
            },
            {
                "category": "fiction",
                "author": "Herman Melville",
                "title": "Moby Dick",
                "isbn": "0-553-21311-3",
                "price": 8.99
            },
            {
                "category": "fiction",
                "author": "J. R. R. Tolkien",
                "title": "The Lord of the Rings",
                "isbn": "0-395-19395-8",
                "price": 22.99
            }
        ],
        "bicycle": {
            "color": "red",
            "price": 19.95
        }
    },
    "expensive": 10
}
```

| JsonPath (click link to try)| Result |
| :------- | :----- |
| <a href="http://jsonpath.herokuapp.com/?path=$.store.book[*].author" target="_blank">$.store.book[*].author</a>| The authors of all books     |
| <a href="http://jsonpath.herokuapp.com/?path=$..author" target="_blank">$..author</a>                   | All authors                         |
| <a href="http://jsonpath.herokuapp.com/?path=$.store.*" target="_blank">$.store.*</a>                  | All things, both books and bicycles  |
| <a href="http://jsonpath.herokuapp.com/?path=$.store..price" target="_blank">$.store..price</a>             | The price of everything         |
| <a href="http://jsonpath.herokuapp.com/?path=$..book[2]" target="_blank">$..book[2]</a>                 | The third book                      |
| <a href="http://jsonpath.herokuapp.com/?path=$..book[2]" target="_blank">$..book[-2]</a>                 | The second to last book            |
| <a href="http://jsonpath.herokuapp.com/?path=$..book[0,1]" target="_blank">$..book[0,1]</a>               | The first two books               |
| <a href="http://jsonpath.herokuapp.com/?path=$..book[:2]" target="_blank">$..book[:2]</a>                | All books from index 0 (inclusive) until index 2 (exclusive) |
| <a href="http://jsonpath.herokuapp.com/?path=$..book[1:2]" target="_blank">$..book[1:2]</a>                | All books from index 1 (inclusive) until index 2 (exclusive) |
| <a href="http://jsonpath.herokuapp.com/?path=$..book[-2:]" target="_blank">$..book[-2:]</a>                | Last two books                   |
| <a href="http://jsonpath.herokuapp.com/?path=$..book[2:]" target="_blank">$..book[2:]</a>                | Book number two from tail          |
| <a href="http://jsonpath.herokuapp.com/?path=$..book[?(@.isbn)]" target="_blank">$..book[?(@.isbn)]</a>          | All books with an ISBN number         |
| <a href="http://jsonpath.herokuapp.com/?path=$.store.book[?(@.price < 10)]" target="_blank">$.store.book[?(@.price < 10)]</a> | All books in store cheaper than 10  |
| <a href="http://jsonpath.herokuapp.com/?path=$..book[?(@.price <= $['expensive'])]" target="_blank">$..book[?(@.price <= $['expensive'])]</a> | All books in store that are not "expensive"  |
| <a href="http://jsonpath.herokuapp.com/?path=$..book[?(@.author =~ /.*REES/i)]" target="_blank">$..book[?(@.author =~ /.*REES/i)]</a> | All books matching regex (ignore case)  |
| <a href="http://jsonpath.herokuapp.com/?path=$..*" target="_blank">$..*</a>                        | Give me every thing   
| <a href="http://jsonpath.herokuapp.com/?path=$..book.length()" target="_blank">$..book.length()</a>                 | The number of books                      |

**Working Example**
---
1. There is an user.

<img width="791" alt="2018-03-27 9 52 32" src="https://user-images.githubusercontent.com/13447690/37968481-2fab97d6-3209-11e8-8535-fbefad8ee775.png">

---
2. After logging in, IAM return the user's token which is encrypted with the value of `gitlabToken`.

<img width="457" alt="2018-03-27 9 58 47" src="https://user-images.githubusercontent.com/13447690/37968819-29d376ac-320a-11e8-889a-cf47e04a2418.png">

---
3. Let's see zuul router configuration.

```
zuul:
  metadata-encoder-secret1: Bar12345Bar12345
  metadata-encoder-secret2: ThisIsASecretKet
  secure-metadata-fields:
    - "$.gitlabToken"

  routes:
    gitlab:
      url: http://gitlab.pas-mini.io/api/v4/
      stripPrefix: true
      addHeader:
        PHONE: "010-0000-0000"
        EMAIL: "$.email"
        PRIVATE-TOKEN: "$.gitlabToken"
```

The above configuration will be sent with the following header, with proxy communication for the `/gitlab` pass.

 - `PHONE` is not starts with `$`, it will use just string `010-0000-0000`
 - `EMAIL` is starts with `$`, it will use metadata email value, `jyjang@uengine.org`
 - `PRIVATE-TOKEN` is already listed in `secure-metadata-fields`, so it will use 
decoded value of gitlabToken, `2A_LokKTbnywjw8shHy-`

---

### Step1. Download [iam-api-2.0.1.js](https://github.com/TheOpenCloudEngine/uEngine-iam/blob/master/iam-javascript-client/iam-api-2.0.1.js)

In your front-end web, replace `static/iam-client/iam-*.js` to `static/iam-client/iam-api-2.0.1.js`

Also replace text In `index.html` 

```
<script type="text/javascript" src="/static/iam-client/iam-api-2.0.1.js"></script>
```

---
### Step2. IAM application.yml

Your IAM has `cloud-server` and `bpm` scopes basically.

```
scopes:
  - name: cloud-server
    description: 클라우드 서버 접근을 허용합니다.
  - name: bpm
    description: bpm 서비스를 사용합니다.
```

If your client need both `cloud-server` and `bpm` scopes to work well, 
You must fill in `enable-scopes` as follows:

```
clients:
  - name: uEngine-cloud
    description: uEngine cloud Application
    clientKey: my-client-key
    clientSecret: my-client-secret

    # 토큰 발급시 요청할 수 있는 스코프 목록.
    enable-scopes: cloud-server,bpm
```

---
### Step3. Edit User's scope

After IAM booted,  go to [http://iam.pas-mini.io](http://iam.pas-mini.io). Default admin login id-password is `admin`,`admin`

Create or modify user.

<img width="797" alt="2018-03-28 12 45 08" src="https://user-images.githubusercontent.com/13447690/37978565-4d700550-3221-11e8-90fc-7f80d747828a.png">

Let's just check the 'cloud-server' scope on the screen.

### Step4. Login from front-web

At `router/index.js` , add router with scopes as follows:

```
{
      path: '/auth/:command',
      name: 'login',
      component: Login,
      props: {
        iamServer: iamUrl,
        scopes: "cloud-server,bpm"
      },
      beforeEnter: RouterGuard.requireGuest
    }
```

Run.

```
npm install
npm run dev
```

Your login page looks like:

<img width="352" alt="2018-03-28 12 54 23" src="https://user-images.githubusercontent.com/13447690/37979085-9fdf5c04-3222-11e8-9508-a8811eff7ed1.png">

By default, users can log in even if they only have a `cloud-server` scope. If you want users to be able to log in with all requested scopes, you must set the following in IAM `application.yml`:

```
clients:
  - name: uEngine-cloud
    ....
    user-scope-check-all: true
```

### Step5. Check token

After login, copy access_token from browser tool.

<img width="928" alt="2018-03-28 1 01 09" src="https://user-images.githubusercontent.com/13447690/37979444-935f10ea-3223-11e8-9b4f-efecc24868d2.png">

Go to [https://jwt.io/](https://jwt.io/) and paste token.

<img width="508" alt="2018-03-28 1 02 25" src="https://user-images.githubusercontent.com/13447690/37979574-ddf6e97a-3223-11e8-922c-7632378a5073.png">

There is only `cloud-server` scope, Because User has requested two scopes, but the user has only one scope.

### Step6. Use token `v-if`

Iam javascript client has scopes and user, you can use it as follows:

```
<div v-if="iam.scopes.includes('cloud-server')">
             {{iam.user.userName}} has cloud-server scope.
</div>
<div v-if="iam.scopes.includes('bpm')">
            {{iam.user.userName}} has bpm scope.
</div>
```
